### ISSUE TITLE
MutationObserver in IE10

### ISSUE THREAD

**Issue by shentao** [vue-comps/vue-clusterize#10]
Hey! 

I know that IE10 doesn’t support MutationObserver. Vue fallbacks to setTimeout for such cases.
However vue-clusterize somehow throws an error when run on IE9-10. 
`mutationObserver is undefined`
I’ve been looking into your code and it doesn’t use the MutationObserver directly, so it’s hard for me to guess where the problem originates. 

Do you plan on supporting IE10? 
If not, it might be a good idea to add info about supported browsers to readme.md.

**Comment by paulpflug** [comment]
Sure I wanna support what I can.
I will have to do some digging, how vue is handling this exactly, basically 
I copied the mechanism of v-for.
Maybe something changed in the last version?

Am 15. Juli 2016 11:24:40 schrieb Damian Dulisz notifications@github.com:

**Comment by shentao** [comment]
The project I am working on uses 1.0.24 right now, so it might not be related to the last 3 versions.

Well besides this small problem, the component works great! Good job! 👍 

If I could have a request – have you thought about a version which supports tables?
Right now even with custom CSS styles that change the display property, it doesn’t seem to work, because you can’t nest `tbody` inside `tbody` nor `tr` inside `tr`.

**Comment by shentao** [comment]
I did some investigation and found out that the problem comes from:
https://github.com/paulpflug/vue-mixins/blob/master/src/onElementResize.coffee

**Comment by paulpflug** [comment]
OK then it will be an easy fix, thanks for looking into it. I will work 
something out later today

**Comment by shentao** [comment]
That would be awesome! 👻

**Comment by paulpflug** [comment]
ok there is a new vue-mixins (0.2.11) it _should_ install on a `npm install`

regarding table: that wont be easy.
current structure:

```
div.clusterize
  div.cluster
    your row
    your row
    ...
  div.cluster
    your row
    your row
    ...
  div.cluster
    your row
    your row
    ...
```

this could translate to this:

```
table.clusterize
  tbody.cluster
    tr
    tr
  tbody.cluster
    tr
    tr
  tbody.cluster
    tr
    tr
```

but this would require nearly twice the template size.

what is your use case?

Have you considered https://github.com/vue-comps/vue-data-table?

**Comment by shentao** [comment]
I didn’t and it actually looks like something I could use. Too late I already made a solution based on grid that simulates a table, but if I have time to refactor I will change it to the data-table solution.
Thanks for your quick fix!
