### ISSUE TITLE
createAnchor

### ISSUE THREAD

**Issue by rendom** [vue-comps/vue-clusterize#2]
Not sure if I'm doing something wrong or if this library is broken with latest vue? Is this project active?
I get following error **Uncaught TypeError: Cannot read property 'createAnchor' of undefined**

```
this.end = this.Vue.util.createAnchor('clusterize-cluster-end');
```

**Comment by paulpflug** [comment]
Yes this project is active.
This problem is related to vuejs#2339.
How did you create your root instance of vue?

Am 18. Mai 2016 11:05:01 vorm. schrieb rendom notifications@github.com:

**Comment by rendom** [comment]
Fyi, I'm using Browserify+Vueify.

main.js

```
var Vue = require('vue')
new Vue({
    el: 'body',
    components: {
        Foo,
        Bar
    }
})
```

**Comment by paulpflug** [comment]
Thanks. Did it work with a previous version of vue?

Am 18. Mai 2016 1:58:41 nachm. schrieb rendom notifications@github.com:

**Comment by rendom** [comment]
https://github.com/vue-comps/vue-clusterize/pull/4 :)

Btw, I can't get the dev environment working here, so can you please push a new build?

**Comment by paulpflug** [comment]
hey, I'm sorry man, https://github.com/vuejs/vue/commit/3f5c9166ea51e81dc59b97d43a4b42304b6c74e3 (>=v1.0.24) broke vue-clusterize. I'm currently unable to provide a working build.

I will have to figure something out...

**Comment by paulpflug** [comment]
I published 0.3.0, should work now. :smile:

**Comment by Teknologica** [comment]
I'm having a similar issue `TypeError: this.Vue.util is undefined` using Vue `1.0.24` and `vue-clusterize 0.3.0`. Using Webpack with Vue loader. It seems the mixin for Vue (this.Vue) isn't working, it is installed however. I haven't been able to find a solution so far.

**Comment by paulpflug** [comment]
@Teknologica 

Ok, I can't reproduce, but this is an important error. I need a reliable way to get the Vue instance from within the component to get clusterize working (https://github.com/vuejs/vue/issues/2339)

This is my current try:
https://github.com/paulpflug/vue-mixins/blob/master/src/vue.coffee

You could help me:
- how did you include Vue? require("Vue")?
- how did you create your root instance?

I tried with the [Vue-webpack-simple](https://github.com/vuejs-templates/webpack-simple)

``` js
import Vue from 'vue'
import App from './App.vue'
new Vue({
  el: 'body',
  components: { App }
})
```

And in `App.vue` the `vue-mixins/vue` is working and giving the Vue instance.

**Comment by Teknologica** [comment]
I think the error is caused by the different project structure I used. For the router I have [Voie](https://github.com/inca/voie). It doesn't setup like the official router. I got it working temporarily by modifying the distribution files to include `var Vue = require("vue");` and changed `this.Vue` where required. I did stumble into another error afterwards `height of row is 0` but that's another issue, probably caused by the fact the content is not displayed at init.

My structure is a mix of this [Voie example](https://github.com/inca/voie-starter-webpack/blob/master/src/main.js) (root instance) and the official webpack template for Vue. My guess is that there is no accessible Vue instance within Voie and how it bootstraps components up.

**Comment by paulpflug** [comment]
your data object needs at least 1 row, you can postpone the init of clusterize with the `v-bind:auto-start=false` attribute and call `start()` on the component instance later, once you have the data 

or simply use the dynamic data callback:
https://github.com/vue-comps/vue-clusterize#dynamic-data
example:
https://github.com/vue-comps/vue-clusterize/blob/master/dev/loading.vue

I will look into Voie, thanks for pointing :smile:

**Comment by paulpflug** [comment]
@Teknologica
I tried Voie, but it worked for me..

I pushed a new version of vue-mixins (0.2.9) with a more robust way of getting the Vue instance, anyway. It "should" get installed if you reinstall vue-clusterize. Could you try it and report back?

**Comment by Teknologica** [comment]
@paulpflug Due to the time constraints on the project we had to use a lesser solution. I will revisit this in the future and let you know the results. Thanks for the help!
