### ISSUE TITLE
Throw "Cannot read property 'getBoundingClientRect' of undefined" when data is empty(first-load)

### ISSUE THREAD

**Issue by codehz** [vue-comps/vue-clusterize#6]
``` JavaScript
this.rowHeight = this.clusters[0].$el.children[1].getBoundingClientRect().height;
```

and this.clusters[0].$el.children[1] is undefined....

I suggest that lazy calculate the height or using a default row height....

**Comment by paulpflug** [comment]
Right, I removed the warning.

There are 2 ways of laziness already:

``` html
<clusterize manual-start v-ref:cluster>
```

and

``` js
   this.$refs.cluster.start() // once data is available
```

or use the [dynamic data](https://github.com/vue-comps/vue-clusterize#dynamic-data) functionality

The current implementation is, that if the data prop isn't set, the dynamic data comes into play.
For your suggested laziness I would need to uses dynamic data only when a flag is set, and if not it will wait for data. That wouldn't be a bad idea, I think.

**Comment by codehz** [comment]
it seems that dynamic data functionality does not respond to the data source (the length) changes..#7 
Some data like playList often is empty, and sometimes is not empty (at init time)...Do I need to consider two cases?
Height of the list items in most cases can be determined in advance. It needn't be calculated at running time.

**Comment by paulpflug** [comment]
There are many factors determining the row-height (like font-size of the browser) I see no way of knowing that before running time?
But I added a prop `row-height` in 0.4.6, where you can set the height in px and which will disable the auto-detection.

**Comment by codehz** [comment]
Sometimes the list item contains a fixed size image....

```
+-------+--------------------+
| image | text               |
|       | text               |
+-------+--------------------+
+-------+--------------------+
| image | text               |
|       | text               |
+-------+--------------------+
```

the image is square....
So this is no reason to calculate the height
