### ISSUE TITLE
redraw() does not work....

### ISSUE THREAD

**Issue by codehz** [vue-comps/vue-clusterize#7]
``` JavaScript
   watch: {
        playList() {
            console.log('update');
            this.$refs.cluster.redraw();
            // or this one: setTimeout(() => this.$refs.cluster.redraw(), 500);
        }
    },
```

and i see 'update at console,but list had not updated until i scroll it.
PS: playList is an async function array so it couldn't be binding directly.

But below is worked

``` JavaScript
    watch: {
        playList() {
            console.log('update');
            let x = this.$refs.cluster.$el.scrollTop;
            this.$refs.cluster.$el.scrollTop = x + 1;
            setTimeout(() => this.$refs.cluster.$el.scrollTop = x, 500);
        }
    }
```

How can i use this fuction?

**Comment by paulpflug** [comment]
There could be a problem. It will issue a redraw,  but when `this.$refs.cluster.data` didn't change, nothing will happen, so is the `playList` somehow connected to `this.$refs.cluster.data` ? It could be that the watcher fires before the change is propagated.

I think I will add a watcher so `redraw` is automatically called on change of `data` prop.

**Comment by paulpflug** [comment]
Ok I had a bug from the last restructuring which didn't properly call `redraw` on change of data. The watcher was already there to calculate the new clusters and all, but no redraw. Should be fixed in 0.4.4.

I'm unsure if this fixes your problem, though, as I'm not fully clear what you are trying to do ;)

So if not, please elaborate your case.

**Comment by codehz** [comment]
I have changed my methods to fetch data
old method:

``` JavaScript
//<clusterize @get-data="getData" @get-data-count="getDataCount" auto-height>
watch: {
    playList() {
        console.log('update');
        this.$refs.cluster.redraw();
    }
},
methods: {
    getData(first, last, cb) {
        //Async is https://www.npmjs.com/package/async
        //fetchFunc will fetch real data(or from cache)
        Async.map(playList.slice(first, last + 1 || 9e9), fetchFunc, (err, data) => cb(data))
    },
    getDataCount(cb) {
        console.log('getCount');//It seems getDataCount only call at first time
        cb(playList.length);
    }
}
```

and now is

``` HTML
<clusterize :data="playList" auto-height>
  <clusterize-row>
   <song-item :data="data" />
  </clusterize-row>
</clusterize>
<!-- song-item will fetch data and display it -->
```

But why the first does not work?

**Comment by paulpflug** [comment]
first should work now with 0.4.5

redraw() didn't fetch the new length.
